import vibepy_core


def test_public_api_is_exported_from_the_package_root() -> None:
    assert vibepy_core.__all__ == [
        "APP_GROUP",
        "ERROR_CATALOG",
        "AppConfig",
        "AppConfigInvalidError",
        "AppDefinition",
        "AppDescription",
        "AppEntrypoint",
        "AppEntrypointInvalidError",
        "AppEntrypointUnloadableError",
        "AppNotDeclaredError",
        "AppRef",
        "Channel",
        "ConfigFieldDescription",
        "ConfigFieldType",
        "DescribedApp",
        "ErrorCategory",
        "ErrorInfo",
        "InvocationRequest",
        "InvokeRequestInvalidError",
        "Lifespan",
        "NoConfig",
        "Page",
        "PageContext",
        "PageDefinition",
        "PageDescription",
        "PageHandler",
        "PageNameConflictError",
        "PageNotFoundError",
        "PageRegistry",
        "PageRouteConflictError",
        "PageRouteInvalidError",
        "PageRuntime",
        "Principal",
        "Tool",
        "ToolContext",
        "ToolDefinition",
        "ToolDescription",
        "ToolForbiddenError",
        "ToolHandler",
        "ToolInputValidationError",
        "ToolInvoker",
        "ToolNameConflictError",
        "ToolNotFoundError",
        "ToolOutputValidationError",
        "ToolRegistry",
        "ToolRuntime",
        "VibepyError",
        "config_fields_of",
        "describe_app",
        "described",
        "discover_apps",
        "environment_for",
        "load_app",
        "page_runtime_for",
        "read_report_line",
        "report",
        "report_line",
        "to_error_info",
        "tool_runtime_for",
    ]


def test_every_exported_name_is_reachable() -> None:
    for name in vibepy_core.__all__:
        assert hasattr(vibepy_core, name)
