"""Agent-native application framework.

The package root is the App author's vocabulary, and an operation a host performs
is reached at its own module. `docs/architecture/app-model.md`, "The import
surface", says which is where; ADR-035 says why.
"""

from vibepy_core.app import (
    AppConfig,
    AppDefinition,
    AppDescription,
    AppEntrypoint,
    ConfigFieldDescription,
    ConfigFieldType,
    DescribedApp,
    Lifespan,
    NoConfig,
    PageDescription,
    ToolDescription,
    WindowRecord,
    page_runtime_for,
    tool_runtime_for,
)
from vibepy_core.channel import Channel
from vibepy_core.errors import (
    ERROR_CATALOG,
    AppConfigInvalidError,
    AppDefinitionInvalidError,
    AppEntrypointInvalidError,
    AppEntrypointUnloadableError,
    AppNotDeclaredError,
    ErrorCategory,
    ErrorInfo,
    InvokeRequestInvalidError,
    PageNameConflictError,
    PageNotFoundError,
    PageRouteConflictError,
    PageRouteInvalidError,
    PageToolUndeclaredError,
    PageToolUnresolvedError,
    ToolChannelsEmptyError,
    ToolForbiddenError,
    ToolInputValidationError,
    ToolNameConflictError,
    ToolNotFoundError,
    ToolOutputValidationError,
    VibepyError,
)
from vibepy_core.page import (
    Page,
    PageContext,
    PageDefinition,
    PageHandler,
    PageRegistry,
    PageRuntime,
    PrincipalToolInvoker,
    ToolInvoker,
)
from vibepy_core.principal import Principal
from vibepy_core.tool import (
    AuthorizationRequest,
    InvocationRecord,
    InvocationRequest,
    Tool,
    ToolContext,
    ToolDefinition,
    ToolHandler,
    ToolPolicy,
    ToolRegistry,
    ToolRuntime,
)

__all__ = [
    "ERROR_CATALOG",
    "AppConfig",
    "AppConfigInvalidError",
    "AppDefinition",
    "AppDefinitionInvalidError",
    "AppDescription",
    "AppEntrypoint",
    "AppEntrypointInvalidError",
    "AppEntrypointUnloadableError",
    "AppNotDeclaredError",
    "AuthorizationRequest",
    "Channel",
    "ConfigFieldDescription",
    "ConfigFieldType",
    "DescribedApp",
    "ErrorCategory",
    "ErrorInfo",
    "InvocationRecord",
    "InvocationRequest",
    "InvokeRequestInvalidError",
    "Lifespan",
    "NoConfig",
    "Page",
    "PageContext",
    "PageDefinition",
    "PageDescription",
    "PageHandler",
    "PageNameConflictError",
    "PageNotFoundError",
    "PageRegistry",
    "PageRouteConflictError",
    "PageRouteInvalidError",
    "PageRuntime",
    "PageToolUndeclaredError",
    "PageToolUnresolvedError",
    "Principal",
    "PrincipalToolInvoker",
    "Tool",
    "ToolChannelsEmptyError",
    "ToolContext",
    "ToolDefinition",
    "ToolDescription",
    "ToolForbiddenError",
    "ToolHandler",
    "ToolInputValidationError",
    "ToolInvoker",
    "ToolNameConflictError",
    "ToolNotFoundError",
    "ToolOutputValidationError",
    "ToolPolicy",
    "ToolRegistry",
    "ToolRuntime",
    "VibepyError",
    "WindowRecord",
    "page_runtime_for",
    "tool_runtime_for",
]
